export *  from "./About/About";
export *  from "./Contact/Contact";
export *  from "./Experience/Experience";
export *  from "./Home/Home";
export *  from "./Works/Works";
export * from "./NavBar/NavBar";
export * from "./Footer/Footer";
export * from "./Modal/Modal";
export * from "./Modal/ModalError";